@baseUrl = http://localhost:3333

# Health Check
GET {{baseUrl}}/health

###

# @name getRooms
GET {{baseUrl}}/rooms

###

# @name createRoom
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
  "name": "Testing Room",
  "description": "This is a test room"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

# @name getRoomQuestion
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# @name createQuestion
POST {{baseUrl}}/rooms/c29fcd44-f720-402e-b624-b7d4a8fb2846/questions
Accept: application/json
Content-Type: application/json

{
  "question": "O que é o react?"
}

